### ISSUE TITLE
Distribution of How to be a Hatcher

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/content-distribution#27]
https://forum.tecommons.org/t/how-you-can-hatch-the-tec/328

**Comment by iviangita** [comment]
**TWITTER: Draft wording for review/approval:** @CommonsBuild/editingteam

We heard you want to advance token engineering and create a regenerative token economy! Wanna know how? Become a founding member of TEC!

Read this step-by-step guide to become one: https://forum.tecommons.org/t/how-you-can-hatch-the-tec/328 

(Meme by Lauren)

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/a79d2b0f-04ba-4ab3-8160-8f841dfd9822)

**Comment by natenatesoo** [comment]
Reviewing!

**Comment by natenatesoo** [comment]
It looks good! "Become a Founding Member" may be a phrase people 'contest' internally, but I see no issues with it.  Other than that, the messaging looks good, and links are included!

Suggestion: 
"Become a founding member of **the** _Token Engineering Commons_!" (prefer to spell it out instead of using the acronym!)

**Comment by iviangita** [comment]
@natenatesoo thank you so much! Will send out the tweet today :D
