### ISSUE TITLE
Update Stewards WG YouTube descriptions

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/content-distribution#34]

**Comment by chuygarcia92** [comment]
Update content descriptions in playlist videos:
https://youtube.com/playlist?list=PLusWL9gf0FITr2aiW-GIJ7-Q43T0u-mwH 

Description drafts can be found here: https://docs.google.com/document/d/116ojz1QerleELqkD3832mvImZB_09N7bqca6gPIWA1A/edit

**Comment by tamarandom** [comment]
Short and sweet for Community Stewards! I'm updating the doc now. 👍🏽

This is the Working Group where the Community Stewards come together to coordinate workstreams, share experiences and reflect on what is going well and what can be done better in order to achieve the mission of the TEC and best serve our community.

Find us on the #stewards channel on our Discord!
