### ISSUE TITLE
Create a graphic for MVV and tweet about it 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/content-distribution#43]
@liviade1

**Comment by liviade1** [comment]
**Vision**
Enable the creation of ethical, safe, resilient and diverse economic systems to benefit societies around the world.
**Mission**
Our goal is to become a Schelling Point for the token engineering community.
Our economic layer will fund projects that discover, develop and proliferate the best practices  for engineering safe tokenized economies, while aligning our collective success with the individual benefit of token holders.
Our social layer is even more important, as it will unite the token engineering field around the ethical principles, standards, tools and methodologies that emerge as this nascent field advances. 
**Values** 
Our Commons operates from a prosocial, human-centered perspective and prioritizes the advancement of token engineering over short-term profits.
Integrity, curiosity, constructive inquiry, presence and gratitude are foundational for maintaining mutual respect within our growing community.
We encourage our members to be radically open source, non-hierarchical, transparent in their intentions and accountable for their actions.

**Comment by iviangita** [comment]
Twitter has character limit, so it's better to put the MVV in graphics and create a tweet thread. Here's from the [original copy](https://docs.google.com/document/d/1R8yLfht6GvGHr8VDvyZ-sVP1s54rPLY4MtXPBOqHtO0/edit#) that @liviade1 drafted and I created the graphics :) 

@CommonsBuild/communications @CommonsBuild/editingteam For approval to be published please. Edits/suggestions are welcome! :D 

**Tweet 1 (part 1)**

The TEC is the 1st DAO to collectively decide its mission, vision & values before launch. We are proud to be a community- designed economy since day 1 of our Cultural Build! 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/a064f90e-9510-40f7-94fb-cb21c03b5130)

**Tweet 1 (part 2) with 3 graphics**

Our mission, vision and values:
![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/9fa93bc3-1f69-418e-bc67-f70597df12ef)
![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/a265cab9-801c-45f0-bfa6-bf38e437b80b)
![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/db577acc-4e76-459b-99fc-f6f77cb920e4)

**Comment by markoprljic** [comment]
I'd break it up in 4 tweets, intro, then mission, vision and values with photo. Also, add hashtags and links to our site.

**Comment by iviangita** [comment]
@markoprljic Will break it up in 4 tweets then. However, I don't think there's already an official post/article about the MVV results in our forum or Medium, can we share the link in another tweet once it's posted in any of our sites?

**Comment by markoprljic** [comment]
Yes I think we can do that. But in these 4 we can just link to our dot org site.

**Comment by jessicazartler** [comment]
LOVE it!!!! :D <3

**Comment by iviangita** [comment]
Published: https://twitter.com/tecmns/status/1389601002836291590

**Comment by liviade1** [comment]
thanks so much @iviangita @markoprljic
