### ISSUE TITLE
Announce params parties on Twitter

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/content-distribution#48]

**Comment by iviangita** [comment]
Reusing the copy that @natenatesoo wrote for param parties last week, but I added the dashboard link and created a graphic. @CommonsBuild/communications @CommonsBuild/editingteam For review/approval please before I publish today (May 11), thank you!!! 

**DRAFT TWEET:**

Token Engineering Challenge!

Come test your skills during one of our Param Parties TODAY and submit the best set of parameters for our upcoming Hatch! 

Join us on Discord: https://discord.gg/NYaBbjTqh8 
Submit your own set of params here: http://params.tecommons.org/hatch 

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/0f29297e-9c07-4ba1-82d7-45e6000033e3)

**Comment by danelsuga** [comment]
Looks great. Tiny edit:

Come test your skills during one of our Param Parties TODAY **[INSERT COMMA]** and submit the best set of parameters for our upcoming Hatch!

**Comment by iviangita** [comment]
@danelsuga will add a comma then, thanks so much for the edit! :)

**Comment by iviangita** [comment]
Here's the final version of the tweet and graphic after reviewing it with @tamarandom. Publishing! :)


Token Engineering Challenge!

Last chance to test your skills during one of our Param Parties TODAY, and submit the best set of parameters for our upcoming Hatch!

Join us on Discord: https://discord.gg/NYaBbjTqh8

Submit your own set of params here: http://params.tecommons.org/hatch

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/b4f7dfaf-22c3-4db2-99c0-db27f5567527)

**Comment by danelsuga** [comment]
Wait! I was wrong about the comma!

**Comment by iviangita** [comment]
@danelsuga edited to remove the comma, include DAOhaus Discord link and fit in Twitter! I also updated the graphic @tamarandom. Posting if no more changes! :)

**TWEET**

Last chance to test your token engineering skills during one of our PARAM PARTIES TODAY and submit the best set of parameters for our upcoming Hatch!

TEC Discord: https://discord.gg/NYaBbjTqh8
DAOhaus Discord: https://discord.gg/Wmdju9BUSu
Submit your params here: http://params.tecommons.org/hatch

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/44833049-85fa-4f7b-a8d7-d18f123fe970)

**Comment by iviangita** [comment]
Closing! 

https://twitter.com/tecmns/status/1392100563970523140?s=20

**Comment by jessicazartler** [comment]
@danelsuga @iviangita just some feedback - I would say as well that we can't assume that people know what "params" are, I think it would be helpful to link your article Suga, or our what's in a hatch article so people have some context in any Tweets that go out.

Also maybe rather than "test your skills" (as many of us don't have these skills and are still learning) maybe "Be a part of designing our token economy" or "be a part of history in the making, as we open our economic design to the community" - to me that says wow, what an opportunity and makes it a little more clear the seriousness or impactful the work actually is, rather than just fun and games (which is also important :D the meme suits for that).

Maybe the graphic can say :
Param Parties
Learn and participate in designing the TEC economy

It's fine if this already went out, but I would suggest incorporating some of this feedback for any further Comms about this process. Thank you for all of your hard work!
