### ISSUE TITLE
Resuscitate TEC's LinkedIn Account

### ISSUE THREAD

**Issue by mount-manu-zz** [CommonsBuild/content-distribution#75]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@chuygarcia92

**Comment by chuygarcia92** [comment]
I personally think we have a bunch on our plate already. I also have never really got LinkedIn, if there's anyone in the community that feels we're missing out on some benefits in this platform we could look for someone to handle updates, but otherwise I'd suggest to close this issue in the meantime (at least until we start funding proposals)

**Comment by mount-manu-zz** [comment]
As Yoda would put it: Closed, this has been.
